services:

  db:
    image: mongo:7
    container_name: mindvault-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
  mindvault-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    image: ${DOCKERHUB_USERNAME:-local}/mindvaultcicd-mindvault-backend:${IMAGE_TAG:-latest}
    container_name: mindvault-backend
    env_file:
      - ./backend/.env
    restart: unless-stopped

    ports:
      - 3000:3000
    depends_on:
      - db
  
  mindvault-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-local}/mindvaultcicd-mindvault-frontend:${IMAGE_TAG:-latest}
    container_name: mindvault-frontend
    restart: unless-stopped
    ports:
      - 5473:5473
    depends_on:
      - db

volumes:
  mongodb_data: